### ISSUE TITLE
Images in the pdf results have some kind of transparency, instead of rendering fully opaque 

### ISSUE THREAD

**Issue by arthur-v-abogadil** [elibyy/tcpdf-laravel#33]
Hello! Thanks for your work on this package. 

I have an issue where the images seem to have some transparency instead of rendering full color,

Please see page 2 of this pdf,
http://customizer.prolook.com/design_sheets/A6D6B362-32E6-5154-93EB-59FC24258811.pdf

Also theres a small thumbnail of a mascot on page 5, the appear to have some king of transparency setting. 

The full color of the image which is also the same as the source image being used by the pdf is at 
https://s3-us-west-2.amazonaws.com/uniformbuilder/uploads/staging/884ab11e1d16911d3d41aae1334ca4b9.png

Thanks! Any help would be really appreciated. 

Arthur

**Comment by elibyy** [comment]
hello,
sorry for the delayed response
since my library is only a wrapper i think you should consult the [TCPDF docs](https://tcpdf.org)
but IMO it's because it's a png with transparent background, so it shouldn't be a problem converting it to JPG with white background for the PDF file

hope this will help

**Comment by arthur-v-abogadil** [comment]
ok this seems to be a good solution, there was an instance right now where we used a different image type (.gif) and it displayed correctly. Thanks for this!
