### ISSUE TITLE
Cannot declare class PDF, because the name is already in use

### ISSUE THREAD

**Issue by mmartinello** [elibyy/tcpdf-laravel#56]
I installed **tcpdf-laravel 5.6** on **Lumen 5.6**.

I registered the class into `bootstrap/app.php`:

```
// TCPDF
$app->register(Elibyy\TCPDF\ServiceProvider::class);
class_alias(Elibyy\TCPDF\Facades\TCPDF::class, 'PDF');
```

But when I try to use it I get this error:

`ErrorException: Cannot declare class PDF, because the name is already in use`

If I remove the class_alias declaration I get this (correct) error:

`Error: Class 'PDF' not found`

Where I am wrong?

Thanks!

**Comment by elibyy** [comment]
Hey there,
Could you please try with a different alias, because I just tested and worked for me.
Also, you might have additional dependencies that might cause this.

Thanks

**Comment by dzanotelli** [comment]
Hi, I experimented the same issue, with any alias. I managed to solve the Error updating the alias definition as follows:

bootstrap/app.php
```
if (!class_exists('PDF')) {
    class_alias(Elibyy\TCPDF\Facades\TCPDF::class, 'PDF');
}
```

**Comment by elibyy** [comment]
@decibel83 Can i close this issue or you're still having trouble?

**Comment by dzanotelli** [comment]
I have just a last question: my workaround does work, but why should I use it and check for the class existence? It seems like the app is bootstrapped more than one time, since no other packages is implementing that alias/class if I comment out the TCPDF declaration.

I inserted a "bootstrapping app ..." message in my ``bootstrap/app.php`` and run a single method from a unittest and that's my output:

```
$ php7.2 phpunit --filter testBuildPdf
bootstrapping app ...PHPUnit 7.2.6 by Sebastian Bergmann and contributors.

1 / 1 (100%)bootstrapping app ...

Time: 77 ms, Memory: 20.00MB
```

As you can see the "bootstrapping app ..." string is there two times. Another possibility I'm thinking right now is that this issue will appear only running the unittest (maybe the phpunit workflow runs more than once the bootstrap sequence but the main laravel/lumen does it correctly once).

I understand that this may be related more with the lumen framework rather with the TCPDF package, but any kind suggetion of you will be really appreciated.

Best,
D.

**Comment by elibyy** [comment]
you should try and trace it down using [debug_backtrace](http://php.net/manual/en/function.debug-backtrace.php) which should provide you with more info about the origin of the call.
